# Use an official OpenJDK runtime as a parent image
FROM openjdk:17-jdk-alpine

# Copy the current directory contents into the container at /app
COPY target/api-gateway-1.0-SNAPSHOT.jar /api-gateway.jar

# Run the jar file
ENTRYPOINT ["java", "-jar", "/api-gateway.jar"]
